/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.Vehiculo;
import Modelo.Chofer;
import java.util.ArrayList;
import java.util.List;
import java.util.Comparator;
import javax.swing.JOptionPane;



public class frmFlotayChofer extends javax.swing.JFrame {
    List<Vehiculo> lista1 = new ArrayList<>();
    List<Chofer> lista2 =new ArrayList<>();
    private boolean ordenAZAsc = true;
    private boolean ordenFechaAsc = true;
    private boolean ordenTipoAsc = true;

    public frmFlotayChofer() {
        initComponents();
        iniciar1();
        iniciar2();
        iniciar3();
    }
    
    public void iniciar1(){
        Vehiculo c1 = new Vehiculo("VAN", "Hyundai", 2018,"Gris", "AEF-005", "28/05/2020", "Petroleo");
        Vehiculo c2 = new Vehiculo("Furgon", "JAC", 2022,"Blanco", "TRM-853", "16/06/2023", "GLP");
        Vehiculo c3 = new Vehiculo("VAN", "Renault", 2020,"Gris", "UPS-482", "08/06/2022", "Gasolina");
        lista1.add(c1);
        lista1.add(c2);
        lista1.add(c3);
        
    }
    public void iniciar2(){
        Chofer ch1=new Chofer("Juan", "Artencio", 89563274, "Varon", "12/03/2024", "A - IIb", "Semiprofesional");
        Chofer ch2=new Chofer("Magaly", "Rivas", 54936172, "Mujer", "28/11/2021", "A - IIIc", "Profesional");
        lista2.add(ch1);
        lista2.add(ch2);
    }
    public void iniciar3(){
         cbxFiltar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
        "Ordenar por Marca",
        "Ordenar por Año",
        "Ordenar por Vehiculo"
        }));
     }
    
    public void mostrarHistorial1() {
        for (Vehiculo v : lista1) {
            v.mostrar(jTextAreaVehiculo); // o usa v.toString() y append
            jTextAreaVehiculo.append("\n----------------\n");
        }
    }
    
    public void mostrarHistorial2() {
        for (Chofer ch : lista2) {
            ch.mostrar(jTextAreaChofer); // o usa v.toString() y append
            jTextAreaChofer.append("\n----------------\n");
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaVehiculo = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextAreaChofer = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btnMostrarvehiculo = new javax.swing.JButton();
        btnMostrarchofer = new javax.swing.JButton();
        cbxFiltar = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        radioPetroleo = new javax.swing.JRadioButton();
        radioGasolina = new javax.swing.JRadioButton();
        radioGLP = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        radioVan = new javax.swing.JRadioButton();
        radioFurgon = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtAñoModelo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtFechaRegistroVehiculo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        taResumenVehiculo = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        btnresumenvehi = new javax.swing.JButton();
        btnguardarvehi = new javax.swing.JButton();
        btnRegistrovehiculo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxgenero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        radioProfesional = new javax.swing.JRadioButton();
        radioSemi = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        radiotipo1 = new javax.swing.JRadioButton();
        radiotipo2 = new javax.swing.JRadioButton();
        radiotipo3 = new javax.swing.JRadioButton();
        txtnombreChofer = new javax.swing.JTextField();
        txtApellidoChofer = new javax.swing.JTextField();
        txtDNIChofer = new javax.swing.JTextField();
        txtFechaChofer = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taResumenchofer = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnresumencho = new javax.swing.JButton();
        btnguardarcho = new javax.swing.JButton();
        btnNuevocho = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTextAreaVehiculo.setColumns(20);
        jTextAreaVehiculo.setRows(5);
        jScrollPane3.setViewportView(jTextAreaVehiculo);

        jTextAreaChofer.setColumns(20);
        jTextAreaChofer.setRows(5);
        jScrollPane4.setViewportView(jTextAreaChofer);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel13.setText("Choferes");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel14.setText("Vehiculos");

        btnMostrarvehiculo.setText("Mostrar");
        btnMostrarvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarvehiculoActionPerformed(evt);
            }
        });

        btnMostrarchofer.setText("Mostrar");
        btnMostrarchofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarchoferActionPerformed(evt);
            }
        });

        cbxFiltar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filtrar", " " }));
        cbxFiltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxFiltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jLabel14)
                .addGap(131, 131, 131)
                .addComponent(btnMostrarvehiculo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxFiltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrarchofer)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnMostrarvehiculo)
                                .addComponent(cbxFiltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel13)
                                .addComponent(btnMostrarchofer)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("HISTORIAL DE VEHICULOS Y CHOFERES", jPanel1);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Combustible"));

        buttonGroup4.add(radioPetroleo);
        radioPetroleo.setText("Petroleo");

        buttonGroup4.add(radioGasolina);
        radioGasolina.setText("Gasolina");

        buttonGroup4.add(radioGLP);
        radioGLP.setText("GLP");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(radioPetroleo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioGasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radioGLP, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioPetroleo)
                    .addComponent(radioGasolina)
                    .addComponent(radioGLP))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel5.setText("Marca");

        jLabel6.setText("Color");

        jLabel7.setText("Placa");

        jLabel8.setText("Fecha de Registro");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de Vehiculo"));

        buttonGroup3.add(radioVan);
        radioVan.setText("VAN");

        buttonGroup3.add(radioFurgon);
        radioFurgon.setText("Furgon");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(radioVan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioFurgon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioVan)
                    .addComponent(radioFurgon))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        jLabel9.setText("Año de modelo");

        taResumenVehiculo.setColumns(20);
        taResumenVehiculo.setRows(5);
        jScrollPane2.setViewportView(taResumenVehiculo);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel10.setText("Resumen");

        btnresumenvehi.setText("Mostrar Resumen");
        btnresumenvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresumenvehiActionPerformed(evt);
            }
        });

        btnguardarvehi.setText("Guardar");
        btnguardarvehi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarvehiActionPerformed(evt);
            }
        });

        btnRegistrovehiculo.setText("Nuevo registro");
        btnRegistrovehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrovehiculoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtFechaRegistroVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAñoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnresumenvehi)
                        .addGap(43, 43, 43)
                        .addComponent(btnRegistrovehiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnguardarvehi)
                        .addGap(54, 54, 54))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtAñoModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtFechaRegistroVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel10))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnresumenvehi)
                                    .addComponent(btnguardarvehi)
                                    .addComponent(btnRegistrovehiculo))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REGISTRO DE VEHICULO", jPanel2);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellido");

        jLabel3.setText("N° de Documento de Identidad");

        cbxgenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Varon ", "Mujer", "Otro", "Prefiero no decirlo" }));

        jLabel4.setText("Fecha de Ingreso");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Categoria"));

        buttonGroup2.add(radioProfesional);
        radioProfesional.setText("Profesional");

        buttonGroup2.add(radioSemi);
        radioSemi.setText("Semiprofesional");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(radioProfesional, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSemi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioProfesional)
                    .addComponent(radioSemi))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo Licencia"));

        buttonGroup1.add(radiotipo1);
        radiotipo1.setText("A-IIb");
        radiotipo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiotipo1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiotipo2);
        radiotipo2.setText("A-IIIb");

        buttonGroup1.add(radiotipo3);
        radiotipo3.setText("A-IIIc");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(radiotipo1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiotipo2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radiotipo3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiotipo1)
                    .addComponent(radiotipo2)
                    .addComponent(radiotipo3))
                .addContainerGap())
        );

        taResumenchofer.setColumns(20);
        taResumenchofer.setRows(5);
        jScrollPane1.setViewportView(taResumenchofer);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel11.setText("Resumen");

        jLabel12.setText("Genero");

        btnresumencho.setText("Mostrar Resumen");
        btnresumencho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresumenchoActionPerformed(evt);
            }
        });

        btnguardarcho.setText("Guardar");
        btnguardarcho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarchoActionPerformed(evt);
            }
        });

        btnNuevocho.setText("Nuevo registro");
        btnNuevocho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevochoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtnombreChofer)
                                .addComponent(txtApellidoChofer)
                                .addComponent(txtDNIChofer, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                .addComponent(txtFechaChofer)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel11)))
                        .addContainerGap(37, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnresumencho)
                        .addGap(18, 18, 18)
                        .addComponent(btnNuevocho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnguardarcho)
                        .addGap(55, 55, 55))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtnombreChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnresumencho)
                            .addComponent(btnguardarcho)
                            .addComponent(btnNuevocho))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidoChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDNIChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(cbxgenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFechaChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("REGISTRO DE CHOFER", jPanel3);

        btnCerrar.setFont(new java.awt.Font("Tempus Sans ITC", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 0, 0));
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCerrar)
                        .addGap(32, 32, 32))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCerrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarchoActionPerformed
        Chofer ch=new Chofer();
        ch.setNombre(txtnombreChofer.getText());
        if (txtnombreChofer==null) {
        JOptionPane.showMessageDialog(this, "Debe agregar el nombre del nuevo chofer.");
        return;
        }
        
        ch.setApellido(txtApellidoChofer.getText());
        if (txtnombreChofer==null) {
        JOptionPane.showMessageDialog(this, "Debe agregar el apellido del nuevo chofer.");
        return;
        }
        
        ch.setDNI(Integer.parseInt(txtDNIChofer.getText()));
        String DNITexto = txtDNIChofer.getText().trim();
        if (DNITexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el número de DNI del chofer.");
            return;
        }
        
        ch.setFingreso(txtFechaChofer.getText());
        if (txtFechaChofer==null) {
        JOptionPane.showMessageDialog(this, "Debe agregar la fecha de registro.");
        return;
        }
        
        if (buttonGroup1.isSelected(null)) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un tipo de licencia.");
            return;
        }
        if (radiotipo1.isSelected()) {
            ch.setTlicencia("A-IIb");
        } else if (radiotipo2.isSelected()) {
            ch.setTlicencia("A-IIIb");
        } else if (radiotipo3.isSelected()) {
            ch.setTlicencia("A-IIIc");
        }
        
        if (buttonGroup2.isSelected(null)) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione una categoría.");
            return;
        }
        if (radioProfesional.isSelected()) {
            ch.setCategoria("Profesional");
        } else if (radioSemi.isSelected()) {
            ch.setCategoria("Semiprofesional");
        }
        
        if (cbxgenero.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(this, "Por favor seleccione un género.");
            return;
        }
        if (cbxgenero.getSelectedItem().equals("Varon")) {
            ch.setGenero("Varon");
        } else if (cbxgenero.getSelectedItem().equals("Mujer")) {
            ch.setGenero("Mujer");
        } else if (cbxgenero.getSelectedItem().equals("Otro")) {
            ch.setGenero("Otro");
        } else if (cbxgenero.getSelectedItem().equals("Prefiero no decirlo")) {
            ch.setGenero("Prefiero no decirlo");
        }
        lista2.add(ch);
        
        JOptionPane.showMessageDialog(this, "Registro de Chofer guardado correctamente.");
    }//GEN-LAST:event_btnguardarchoActionPerformed

    private void btnresumenchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresumenchoActionPerformed
        Chofer ch=new Chofer();
        ch.setNombre(txtnombreChofer.getText());
        ch.setApellido(txtApellidoChofer.getText());
        ch.setDNI(Integer.parseInt(txtDNIChofer.getText()));
        ch.setFingreso(txtFechaChofer.getText());
        if (radiotipo1.isSelected()) {
            ch.setTlicencia("A-IIb");
        } else if (radiotipo2.isSelected()) {
            ch.setTlicencia("A-IIIb");
        } else if (radiotipo3.isSelected()) {
            ch.setTlicencia("A-IIIc");
        }

        if (radioProfesional.isSelected()) {
            ch.setCategoria("Profesional");
        } else if (radioSemi.isSelected()) {
            ch.setCategoria("Semiprofesional");
        }

        if (cbxgenero.getSelectedItem().equals("Varon")) {
            ch.setGenero("Varon");
        } else if (cbxgenero.getSelectedItem().equals("Mujer")) {
            ch.setGenero("Mujer");
        } else if (cbxgenero.getSelectedItem().equals("Otro")) {
            ch.setGenero("Otro");
        } else if (cbxgenero.getSelectedItem().equals("Prefiero no decirlo")) {
            ch.setGenero("Prefiero no decirlo");
        }
        ch.mostrar(taResumenchofer);
    }//GEN-LAST:event_btnresumenchoActionPerformed

    private void radiotipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiotipo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radiotipo1ActionPerformed

    private void btnguardarvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarvehiActionPerformed
        Vehiculo v=new Vehiculo();
        v.setColor(txtColor.getText());
        if (txtColor==null) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese el color del vehículo");
            return;
        }
        v.setFregistro(txtFechaRegistroVehiculo.getText());
        if (txtFechaRegistroVehiculo==null) {
            JOptionPane.showMessageDialog(this, "Debe agregar la fecha de registro.");
            return;
        }
        
        v.setMarca(txtMarca.getText());
        if (txtMarca==null) {
            JOptionPane.showMessageDialog(this, "Debe agregar la marca del vehículo.");
            return;
        }
        
        v.setAniomodelo(Integer.parseInt(txtAñoModelo.getText()));
        if (txtAñoModelo==null) {
            JOptionPane.showMessageDialog(this, "Debe agregar el año de modelo del vehículo.");
            return;
        }
        
        v.setPlaca(txtPlaca.getText());
        String PlacaTexto = txtPlaca.getText().trim();
        if (PlacaTexto.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor ingrese la placa del vehículo.");
            return;
        }
        
        if (buttonGroup3.isSelected(null)) {
            JOptionPane.showMessageDialog(this, "Eliga un tipo de vehículo.");
            return;
        }
        if (radioVan.isSelected()) {
            v.setTipov("VAN");
        } else if (radioFurgon.isSelected()) {
            v.setTipov("Furgon");
        }
        
        if (buttonGroup4.isSelected(null)) {
            JOptionPane.showMessageDialog(this, "Eliga el tipo de combustible.");
            return;
        }
        if (radioPetroleo.isSelected()) {
            v.setTipoc("Petroleo");
        } else if (radioGasolina.isSelected()) {
            v.setTipoc("Gasolina");
        } else if (radioGLP.isSelected()) {
            v.setTipoc("GLP");
        }
        lista1.add(v);
        
        JOptionPane.showMessageDialog(this, "Registro de Vehículo guardado correctamente.");
    }//GEN-LAST:event_btnguardarvehiActionPerformed

    private void btnresumenvehiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresumenvehiActionPerformed
        Vehiculo v=new Vehiculo();
        v.setColor(txtColor.getText());
        v.setFregistro(txtFechaRegistroVehiculo.getText());
        v.setMarca(txtMarca.getText());
        v.setAniomodelo(Integer.parseInt(txtAñoModelo.getText()));
        v.setPlaca(txtPlaca.getText());
        if (radioVan.isSelected()) {
            v.setTipov("VAN");
        } else if (radioFurgon.isSelected()) {
            v.setTipov("Furgon");
        }

        if (radioPetroleo.isSelected()) {
            v.setTipoc("Petroleo");
        } else if (radioGasolina.isSelected()) {
            v.setTipoc("Gasolina");
        } else if (radioGLP.isSelected()) {
            v.setTipoc("GLP");
        }
        v.mostrar(taResumenVehiculo);
    }//GEN-LAST:event_btnresumenvehiActionPerformed

    private void btnMostrarchoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarchoferActionPerformed
        mostrarHistorial2();
    }//GEN-LAST:event_btnMostrarchoferActionPerformed

    private void btnMostrarvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarvehiculoActionPerformed
        mostrarHistorial1();
    }//GEN-LAST:event_btnMostrarvehiculoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void cbxFiltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxFiltarActionPerformed

        String opcion = cbxFiltar.getSelectedItem().toString();

        switch (opcion) {
            case "Ordenar por Marca":
                if (ordenAZAsc) {
                    lista1.sort(Comparator.comparing(Vehiculo::getMarca));
                } else {
                    lista1.sort(Comparator.comparing(Vehiculo::getMarca).reversed());
                }
                ordenAZAsc = !ordenAZAsc;
                break;

            case "Ordenar por Año":
                if (ordenFechaAsc) {
                    lista1.sort(Comparator.comparing(Vehiculo::getAniomodelo).reversed()); 
                } else {
                    lista1.sort(Comparator.comparing(Vehiculo::getAniomodelo));
                }
                ordenFechaAsc = !ordenFechaAsc;
                break;

            case "Ordenar por Vehiculo":
            if (ordenTipoAsc) {
                    lista1.sort(Comparator.comparing(Vehiculo::getTipov));
                } else {
                    lista1.sort(Comparator.comparing(Vehiculo::getTipov).reversed());
                }
                ordenTipoAsc = !ordenTipoAsc;
                break;
        }

        // Mostrar resultado en el TextArea
        jTextAreaVehiculo.setText(""); // Limpiar
        for (Vehiculo v : lista1) {
            v.mostrar(jTextAreaVehiculo); // o jTextAreaVehiculo.append(v.toString() + "\n");
            jTextAreaVehiculo.append("\n----------------\n");
        }

    }//GEN-LAST:event_cbxFiltarActionPerformed

    private void btnRegistrovehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrovehiculoActionPerformed
        Vehiculo ve=new Vehiculo();  
        
        txtMarca.setText("");
        txtAñoModelo.setText("");
        
        txtPlaca.setText("");
        txtColor.setText("");
        txtFechaRegistroVehiculo.setText("");
        taResumenVehiculo.setText("");
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
    }//GEN-LAST:event_btnRegistrovehiculoActionPerformed

    private void btnNuevochoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevochoActionPerformed
        Chofer ch=new Chofer();  
        
        txtnombreChofer.setText("");
        txtApellidoChofer.setText("");
        
        txtDNIChofer.setText("");
        cbxgenero.setSelectedIndex(0);
        txtFechaChofer.setText("");
        taResumenchofer.setText("");
        buttonGroup1.clearSelection();
        buttonGroup2.clearSelection();
    }//GEN-LAST:event_btnNuevochoActionPerformed
    private void txtDNIChoferKeyTyped(java.awt.event.KeyEvent evt) {                                      
        if (txtDNIChofer.getText().length()>=8) {
            evt.consume();
        }
    } 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFlotayChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFlotayChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFlotayChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFlotayChofer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFlotayChofer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnMostrarchofer;
    private javax.swing.JButton btnMostrarvehiculo;
    private javax.swing.JButton btnNuevocho;
    private javax.swing.JButton btnRegistrovehiculo;
    private javax.swing.JButton btnguardarcho;
    private javax.swing.JButton btnguardarvehi;
    private javax.swing.JButton btnresumencho;
    private javax.swing.JButton btnresumenvehi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JComboBox<String> cbxFiltar;
    private javax.swing.JComboBox<String> cbxgenero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextAreaChofer;
    private javax.swing.JTextArea jTextAreaVehiculo;
    private javax.swing.JRadioButton radioFurgon;
    private javax.swing.JRadioButton radioGLP;
    private javax.swing.JRadioButton radioGasolina;
    private javax.swing.JRadioButton radioPetroleo;
    private javax.swing.JRadioButton radioProfesional;
    private javax.swing.JRadioButton radioSemi;
    private javax.swing.JRadioButton radioVan;
    private javax.swing.JRadioButton radiotipo1;
    private javax.swing.JRadioButton radiotipo2;
    private javax.swing.JRadioButton radiotipo3;
    private javax.swing.JTextArea taResumenVehiculo;
    private javax.swing.JTextArea taResumenchofer;
    private javax.swing.JTextField txtApellidoChofer;
    private javax.swing.JTextField txtAñoModelo;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtDNIChofer;
    private javax.swing.JTextField txtFechaChofer;
    private javax.swing.JTextField txtFechaRegistroVehiculo;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtnombreChofer;
    // End of variables declaration//GEN-END:variables
}

